baseURL = "http://hrst4.xyz/"
languageCode = "en-us"
title = "hrst4's Blog"

[permalinks]
  blog = "/:filename/"
  
# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Doc"
    pre = "database"
    url = "/docs/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 4

[taxonomies]
  # category = "categories"
  tag = "tags"

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "You just made a Hugo blog from scratch."

