# baseURL = "https://gu1shermo.github.io/website-hrst4/"
baseURL = "https://hrst4.xyz/"
languageCode = 'en-us'
title = "hrst4's blog"
theme =  'PaperMod'

[module]
[[module.mounts]]
source = 'content'
target = 'content'
excludeFiles = ['templates/**']