# baseURL = "https://gu1shermo.github.io/website-hrst4/"
baseURL = "https://hrst4.xyz/"
languageCode = 'en-us'
title = "hrst4's blog toml"
theme =  'PaperMod'

[params]
defaultTheme = "dark"
disableThemeToggle = true
[[params.homeInfoParams]]
Title = "Hi there wave dark theme"
Content = "Can be Info, links, about... dark theme"

[[params.socialIcons]]
name = "kofi"
title = "<custom title> kofi"
url = "https://kofi.com"

[[params.socialIcons]]
name = "twitter"
title = "<custom title> twitter"
url = "https://twitter.com"

[module]
[[module.mounts]]
source = 'content'
target = 'content'
excludeFiles = ['templates/**']

